### ISSUE TITLE
Legal o tradutor

### ISSUE THREAD

**Issue by bigbruno** [rizzini/Dotfiles#1]
Esse não é um issue mesmo, eu achei a referência ao seu github sobre um script para rodar o waydroid no xorg, ele não está mais por aqui, mas achei legal o de tradução e por ver que vc tb é BR e usa ARCH, fica tb o convite para vc aparecer lá no grupo biglinux no telegram, a gente faz muito esse tipo de script que simplifica o dia a dia, seria legal ter mais um no grupo para trocar ideias.

**Comment by rizzini** [comment]
Opa.. Bom dia, Bruno. O script do Waydroid não está no master, pq desinstalei o aplicativo, mas criei um [release](https://github.com/rizzini/Dotfiles/releases/tag/Anbox_and_Waydroid) antes para guardar as configurações do ambiente. Caminho: `Dotfiles-Anbox_and_Waydroid/Documentos/scripts/waydroid.sh`.

Vou instalar o telegram. Aceito o convite sim. Obrigado!

**Comment by bigbruno** [comment]
Fiquei até agora fazendo testes com o waydroid, com as atualizações do weston agora é preciso especificar o socket no weston e o WAYLAND_DISPLAY no waydroid, por exemplo:

WAYLAND_DISPLAY=waydroid waydroid show-full-ui
weston -S waydroid

E o processo de achar o id do android para liberar o do Gapps direto pelo terminal do host e não dentro do waydroid shell:

sudo sqlite3 /var/lib/waydroid/data/data/com.google.android.gsf/databases/gservices.db "select * from main where name = \"android_id\";" | cut -f2 -d"|"
